version: '3.0'
services:

######### CloudStorage ##########
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    hostname: dozzle
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9090:8080

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    volumes:
      - ${USERDIR}/docker/nextcloud/config:/var/www/html/config
      - ${USERDIR}/docker/nextcloud/db:/var/lib/mysql
      - ${USERDIR}/docker/nextcloud/data:/var/www/html/data
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - 'REDIS_HOST_PASSWORD=nextcloud_redis_pass'
    ports:
      - 80:80

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass nextcloud_redis_pass
    restart: unless-stopped

  db:
    image: mariadb
    container_name: db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_DATABASE=db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      #192.168.50.201:3306
    ports:
      - 3306:3306
    volumes:
      - ${USERDIR}/docker/MariaDB/config:/var/www/html/config
      - ${USERDIR}/docker/MariaDB/db:/var/lib/mysql:rw
      - ${USERDIR}/docker/MariaDB/data:/var/www/html/data:rw
    restart: unless-stopped

  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS= #optional
    volumes:
      - ${USERDIR}/docker/duplicati/appdata/config:/config
      - ${USERDIR}/docker/duplicati/backups:/backups
      - ${USERDIR}/docker/duplicati/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped

  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/docker/home-assistant/config:/config
    ports:
      - 8123:8123
    restart: unless-stopped
    privileged: true
    depends_on:
      - db

  # syncthing:
  #   image: syncthing/syncthing
  #   container_name: syncthing
  #   environment:
      # - PUID=${PUID}
      # - PGID=${PGID}
      # - TZ=${TZ}
  #   volumes:
  #     - ${USERDIR}/docker/syncthing:/var/syncthing
  #   ports:
  #     - 8384:8384 # Web UI
  #     - 22000:22000/tcp # TCP file transfers
  #     - 22000:22000/udp # QUIC file transfers
  #     - 21027:21027/udp # Receive local discovery broadcasts
  #   restart: unless-stopped

#   gitlab:
#     image: gitlab/gitlab-ee:latest
#     ports:
#       - "22:22"
#       - "80:80"
#       - "443:443"
#     volumes:
#       - $GITLAB_HOME/data:/var/opt/gitlab
#       - $GITLAB_HOME/logs:/var/log/gitlab
#       - $GITLAB_HOME/config:/etc/gitlab
#     shm_size: '256m'
#     environment:
#       GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
#     configs:
#       - source: gitlab
#         target: /omnibus_config.rb
#     secrets:
#       - gitlab_root_password
#   gitlab-runner:
#     image: gitlab/gitlab-runner:alpine
#     deploy:
#       mode: replicated
#       replicas: 4
# configs:
#   gitlab:
#     file: ./gitlab.rb
# secrets:
#   gitlab_root_password:
#     file: ./root_password.txt

volumes:
  nextcloud:
  db:
