version: "3.3"
services:
  adguardhome:
    image: adguard/adguardhome
    hostname: adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3001:3000/tcp
      - 8082:80/tcp
      - 444:443/tcp
    environment:
      - PUID=1000
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/adguard/workdir:/opt/adguardhome/work
      - ${USERDIR}/adguard/confdir:/opt/adguardhome/conf
    restart: unless-stopped


  vaultwarden:
    container_name: vaultwarden
    hostname: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    volumes:
      - ${USERDIR}/vaultwarden/data/:/data/

    environment:
      - WEBSOCKET_ENABLED=true
      - ROCKET_PORT=8001
      - SIGNUPS_ALLOWED=true
      - SIGNUPS_VERIFY=false
      - INVITATIONS_ALLOWED=false
      - ADMIN_TOKEN=113e78f3faca4aefb078ec72063d1229
      - SHOW_PASSWORD_HINT=false
      - PUID=1000
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 3012:3012
      - 8001:8001

  # vaultwarden-backup:
  #   image: ttionya/vaultwarden-backup:latest
  #   container_name: vaultwarden-backup
  #   hostname: vaultwarden-backup
  #   restart: always
  #   environment:
  #     CRON: '00 03 * * *'
  #     ZIP_ENABLE: 'TRUE'
  #     ZIP_PASSWORD: 'PASSWORD'
  #     ZIP_TYPE: 'zip'
  #     BACKUP_KEEP_DAYS: 30
  #     PUID: 1000
  #     PGID: ${PGID}
  #     TZ: ${TZ}
  #   volumes:
  #     - ${USERDIR}/bw-data:/bitwarden/data/
  #     - ${USERDIR}/vaultwarden-backup/:/config/

  # vaultwarden-backup:
  #   image: ttionya/vaultwarden-backup:latest
  #   container_name: vaultwarden-backup
  #   hostname: vaultwarden-backup
  #   restart: always
  #   environment:
  #     CRON: '00 03 * * *'
  #     ZIP_ENABLE: 'TRUE'
  #     ZIP_PASSWORD: 'PASSWORD'
  #     ZIP_TYPE: 'zip'
  #     BACKUP_KEEP_DAYS: 30
  #     PUID: 1000
  #     PGID: ${PGID}
  #     TZ: ${TZ}
  #   volumes:
  #     - ${USERDIR}/bw-data:/bitwarden/data/
  #     - ${USERDIR}/vaultwarden-backup/:/config/

  # tailscale:
  #   container_name: tailscale
  #   volumes:
  #     - '/var/lib:/var/lib'
  #     - '/dev/net/tun:/dev/net/tun'
  #   network_mode: host
  #   environment:
  #     - PUID=1000
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   privileged: true
  #   image: tailscale/tailscale
  #   entrypoint: tailscaled
