version: "3.3"
services:
  nginxpm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginxpm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
      - '8443:8443'
      - '8444:8444'
      - '8445:8445'
    volumes:
      - ${USERDIR}/nginxpm/data:/data
      - ${USERDIR}/nginxpm/letsencrypt:/etc/letsencrypt
        #nginx:
    #image: nginx
      #container_name: nginx
      #restart: unless-stopped
      #environment:
      #- PUID=${PUID}
        #- PGID=${PGID}
        #- TZ=${TZ}
        #    volumes:
        #- ${USERDIR}/nginx/vaultwarden.conf:/etc/nginx/conf.d/default.conf:ro
        #- ${USERDIR}/nginx/cert/:/etc/nginx/ssl/:ro
        #- ${USERDIR}/nginx/homepage.conf:/etc/nginx/sites-available/:ro

    #ports:
    #- 80:80
    #- 443:443
    #- 8443:8443
    #- 8444:8444
    # - 8445:8445
    # - 8446:8446
    # - 8447:8447
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    hostname: homepage
    container_name: homepage
    restart: always
    environment:
      - PUID=1000
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 3000:3000
    volumes:
      - ${USERDIR}/homepage/config:/app/config
        #      - ${USERDIR}/homepage/public:/app/public
      - /var/run/docker.sock:/var/run/docker.sock
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    hostname: dozzle
    environment:
      - PUID=1000
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9090:8080
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/syncthing/config:/config
      - ${USERDIR}/syncthing/data1:/data1
      - ${USERDIR}/syncthing/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    
  iperf:
    container_name: iperf
    image: networkstatic/iperf3
    command: -s
    restart: unless-stopped
    ports:
      - "50001:5001/tcp"
      - "50001:5001/udp"
    command: iperf3 -s -V -d -p 5001

  netdata:
    container_name: netdata
    image: titpetric/netdata
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    environment:
      - TZ=Europe/Bucharest
      #- PUID=1000
      #- PGID=1000
    ports:
    - 19999:19999
    volumes:
      - /opt/config/netdata:/etc/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8765:80
    volumes:
      - ${USERDIR}/data:/config
    environment:
      - PUID=1000
      - PGID=${PGID}
      - TZ=${TZ}
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
  duplicacy:
    image: erichough/duplicacy
    container_name: duplicacy
    restart: always
    ports:
      - 3875:3875
    cap_drop:
      - ALL
    volumes:
      - ${USERDIR}/duplicacy/config/dir:/etc/duplicacy
      - ${USERDIR}/duplicacy/cache:/var/cache/duplicacy
      - ${USERDIR}/duplicacy/storage:/storage
